In [1]:
# View SQLite basket data
# ------------------------

import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect("baskets.db")

# Load and display baskets
baskets_df = pd.read_sql_query("SELECT * FROM baskets", conn)
print("üß∫ Baskets Table:")
print(baskets_df)

# Load and display basket items
items_df = pd.read_sql_query("SELECT * FROM basket_items", conn)
print("\nüì¶ Basket Items Table:")
print(items_df)

# Optionally merge for full view
merged_df = pd.read_sql_query("""
    SELECT b.id as basket_id, b.timestamp, i.item
    FROM baskets b
    JOIN basket_items i ON b.id = i.basket_id
    ORDER BY b.id
""", conn)
print("\nüîç Full Basket Data:")
print(merged_df)

conn.close()

üß∫ Baskets Table:
    id                         timestamp
0    1  2025-05-29T09:04:30.373390+00:00
1    2  2025-05-29T09:04:31.502320+00:00
2    3  2025-05-29T09:04:32.504750+00:00
3    4  2025-05-29T09:04:33.506624+00:00
4    5  2025-05-29T09:04:34.510239+00:00
5    6  2025-05-29T09:04:35.511985+00:00
6    7  2025-05-29T09:04:36.514248+00:00
7    8  2025-05-29T09:04:37.516573+00:00
8    9  2025-05-29T09:04:38.517461+00:00
9   10  2025-05-29T09:04:39.518453+00:00
10  11  2025-05-29T09:04:40.519610+00:00
11  12  2025-05-29T09:04:41.520903+00:00
12  13  2025-05-29T09:04:42.524303+00:00
13  14  2025-05-29T09:04:43.527026+00:00
14  15  2025-05-29T09:04:44.527836+00:00
15  16  2025-05-29T09:04:45.528551+00:00
16  17  2025-05-29T09:04:46.529511+00:00
17  18  2025-05-29T09:04:47.530562+00:00
18  19  2025-05-29T09:04:48.531692+00:00
19  20  2025-05-29T09:04:49.532964+00:00
20  21  2025-05-29T09:04:50.534866+00:00
21  22  2025-05-29T09:04:51.535691+00:00
22  23  2025-05-29T09:04:52.537738+00:00
23  24  2025-05-29T09:04:53.545168+00:00

üì¶ Basket Items Table:
    id  basket_id                 item
0    1          1         citrus fruit
1    2          1  semi-finished bread
2    3          1            margarine
3    4          1          ready soups
4    5          2       tropical fruit
..  ..        ...                  ...
62  63         24       tropical fruit
63  64         24         cream cheese
64  65         24     processed cheese
65  66         24            detergent
66  67         24           newspapers

[67 rows x 3 columns]

üîç Full Basket Data:
    basket_id                         timestamp                 item
0           1  2025-05-29T09:04:30.373390+00:00         citrus fruit
1           1  2025-05-29T09:04:30.373390+00:00  semi-finished bread
2           1  2025-05-29T09:04:30.373390+00:00            margarine
3           1  2025-05-29T09:04:30.373390+00:00          ready soups
4           2  2025-05-29T09:04:31.502320+00:00       tropical fruit
..        ...                               ...                  ...
62         24  2025-05-29T09:04:53.545168+00:00       tropical fruit
63         24  2025-05-29T09:04:53.545168+00:00         cream cheese
64         24  2025-05-29T09:04:53.545168+00:00     processed cheese
65         24  2025-05-29T09:04:53.545168+00:00            detergent
66         24  2025-05-29T09:04:53.545168+00:00           newspapers

[67 rows x 3 columns]